### ISSUE TITLE
02/04 - Mocked date gives wrong day if time not explicitly set to be after 00:00

### ISSUE THREAD

**Issue by isimmons** [epicweb-dev/testing-fundamentals#14]
In exercise 02 section 04 "Hooks" my test failed. When mocking the date it appears to be defaulting to "2024-01-01:00:00" but the day doesn't actually start until 1 second after that so what I get is "2023-12-31" if I console.log it out.

I fixed it in my code by explicitly setting the time to 1AM

```Javascript
beforeAll(() => {
	globalThis.Date = new Proxy(globalThis.Date, {
		construct: () => new OriginalDate('2024-01-01:01:00'),
	})
})
``` 

I just realized this is a problem on every lesson after this one. Is it something wrong on my end? 

Windows 10, node 20

**Comment by isimmons** [comment]
Yes Sir, here is my output.

```javascript
    const date = new OriginalDate('2024-01-01')
    console.log(date) // 2024-01-01T00:00:00.000Z
    console.log(date.toLocaleDateString()) // 12/31/2023
    console.log(date.toLocaleDateString('en-US', { weekday: 'long' })) // Sunday

    const anotherDate = new OriginalDate('2024-01-01:00:00:00.001')
    console.log(anotherDate) // 2024-01-01T00:00:00.001Z
    console.log(anotherDate.toLocaleDateString()) // 1/1/2024
    console.log(anotherDate.toLocaleDateString('en-US', { weekday: 'long' })) // Monday
```

**Comment by kettanaito** [comment]
@isimmons, hi! Sorry for getting so late to you. 

Can you tell me if this fixes your issue?

```diff
--- a/exercises/02.test-structure/04.solution.hooks/greet.ts
+++ b/exercises/02.test-structure/04.solution.hooks/greet.ts
@@ -1,5 +1,8 @@
 export function greet(name: string) {
-       const weekday = new Date().toLocaleDateString('en-US', { weekday: 'long' })
+       const weekday = new Date().toLocaleDateString('en-US', {
+               weekday: 'long',
+               timeZone: 'UTC',
+       })
 
        return `Hello, ${name}! Happy, ${weekday}.`
 }
```

It's a change you need to do in `greet.ts`: add a `timeZone` property to `.toLocaleDateString()` and set its value to `"UTC"`.

**Comment by kettanaito** [comment]
It's important to mention that it's likely a timezone issue and it gets triggered by setting explicit time on the mock date. Notice that the exercises never provide the time, only the date:

```ts
beforeAll(() => {
  globalThis.Date = new Proxy(globalThis.Date, {
    construct: () => new OriginalDate('2024-01-01'),
  })
})
```

But if you try to provide a date+time string, it will indeed create a previous day (1h before) even in raw Node.js:

```js
new Date('2024-01-01 00:00:00.000')
// 2023-12-31T23:00:00.000Z
```

I suspect this is because Node.js has a default timezone that's not UTC. There are two ways to fix this:

1. Provide an explicit timezone within the date (notice the `Z` at the end, which stands for UTC): 

```js
new Date('2024-01-01 00:00:00.000Z')
// 2024-01-01T00:00:00.000Z
```

2. Provide an explicit timezone on the test process itself:

```sh
TZ=UTC npx tsx ...
```

**Comment by isimmons** [comment]
@kettanaito yes setting the timezone fixes the issue. 

Actually for me, not setting an explicit time in the test, it fails. Setting the time explicit `00:00:00.0001` was my workaround to make it pass. 

But the timezone option in greet.ts fixes it without any need for explicit time.

Thanks
