### ISSUE TITLE
03/02 - Incorrect Promise chaining of .then().catch()

### ISSUE THREAD

**Issue by ssmkhrj** [epicweb-dev/testing-fundamentals#17]
Hey @kettanaito, just wanted to point out a BUG that I found in the **Promise Rejections** module.

So, this is how we implemented `rejects.toThrow` utility, which works fine when `actual` is a **rejected promise** but it doesn't work as expected when `actual` becomes a **resolved promise**.
 
```ts
globalThis.expect = function (actual: unknown) {
  return {
    rejects: {
      toThrow(expected) {
        if (!(actual instanceof Promise)) {
          throw new Error(`Expected ${actual} to be a promise`);
        }

        return actual
          .then(() => {
            throw new Error(`Expected ${actual} to reject but it didn't`);
          })
          .catch((error) => {
            if (error.message !== expected.message) {
              throw new Error(
                `Expected ${error.message} to equal to ${expected.message}`,
              );
            }
          });
      },
    },
  };
};
```

**Explanation:**
So, we do try to handle cases where `actual` gets resolved instead of rejected but the error that we throw in the `then` block gets caught in the `catch` block, so the error that gets logged is the one from the `catch` block and not the one from the `then` block.

Fix is to simply pass the `catch` handler as the second argument to `then` so that the error thrown in `then` is NOT caught and gets logged.
```ts
globalThis.expect = function (actual: unknown) {
  return {
    rejects: {
      toThrow(expected) {
        if (!(actual instanceof Promise)) {
          throw new Error(`Expected ${actual} to be a promise`);
        }

        return actual.then(
          () => {
            throw new Error(`Expected ${actual} to reject but it didn't`);
          },
          (error) => {
            if (error.message !== expected.message) {
              throw new Error(
                `Expected ${error.message} to equal to ${expected.message}`,
              );
            }
          },
        );
      },
    },
  };
};
```

**Comment by kettanaito** [comment]
Hi, @ssmkhrj. You are totally right, my bad! 

The order of `.then` and `.catch` has to be swapped. That's the easiest solution to the problem. You can also use a single `.then(onResolved, onRejected)` callback, that'd work too! 

Let me think about the best way to address this in the workshop.

**Comment by ssmkhrj** [comment]
Hi @kettanaito, unfortunately swapping the order of `then` and `catch` would also NOT work as it would cause a different issue.

So, in happy path scenarios, where `actual` is a rejected promise with correct message, `catch` would NOT throw anything which means `catch` would return a resolved promise which would then trigger the `then` callback resulting in the `Expected ${actual} to reject but it didn't` error.

**Comment by kettanaito** [comment]
That's a good point 👍 Thanks for pointing it out, I didn't consider successful scenarios (when the promise rejects).

**Comment by kettanaito** [comment]
@ssmkhrj, I've opened a pull request to address this mistake in the exercise solution: #18. If you can take a look at it, I'd be grateful! Once again, thanks for pointing this out.

**Comment by ssmkhrj** [comment]
@kettanaito PR LGTM, thanks for addressing it!
